/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>
#include <includes.h>

/**********************************************************/
/*  Name        : PWM Generation           		          */
/*  Parameters  : Interrupt function                      */
/*  Returns     : none                                       */
/*  Function    : to set the PWM Pins based on value of cnt  */
/*                         WO0   WO1 */
/*                  OVF  =  0     0  */
/*                  CMP1 =  1     0  */
/*                  CMP2 =  0     0  */
/*                  CMP3 =  0     1  */
/* The points that are set are done in the user code                    */
/*  Waveform has Deadtime, soft start 10 Cycles, soft stop 10 Cycles    */
/*  hence the need to use the ints rather than the WF gen function  */
/*--------------------------------------------------------*/
ISR(TCA0_OVF_vect)
{
	/* Overflow one 1/2 cycle complete */
    WO1_set_level(false);
    WO0_set_level(false);
    Run_set_level(true);
	/* The interrupt flag has to be cleared manually */
	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_OVF_bm;
}


ISR(TCA0_CMP0_vect)
{  
    /*Dead time complete */
	/* Count reached here turn on Drive A or B */
 //   if(SD_wait_cntr > MAX_SD_WAIT )
 if((nEN_get_level() == PSU_ON ) && (nMAXDTY_get_level()== PSU_ON))
    {
        if (Pwm_Drv_Channel > 0)
            {
            WO1_set_level(false);
            WO0_set_level(true);       /* Drive A */
            Pwm_Drv_Channel = 0;
            }
        else
            {
            WO1_set_level(true);       /* Drive B */
            WO0_set_level(false);
            Pwm_Drv_Channel = 1;
            }
        }
    else
        {
        WO1_set_level(false);
        WO0_set_level(false);
        SD_wait_cntr++;
        }
    Run_set_level(true);
	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_CMP0_bm;	/* The interrupt flag has to be cleared manually */
}

ISR(TCA0_CMP1_vect)
{
	/* end of half cycle restart timer */
    WO0_set_level(false);
    WO1_set_level(false);
    Run_set_level(true);
 
//    if(nEN_get_level() == PSU_ON ) 
//       {
//         if(SD_wait_cntr > MAX_SD_WAIT )
//            {
//           if( softstart < softstart_max )   /* softstart stepping up to desired level.*/
//                {
//                softstart++;
//                softstop = softstart;
//                }
//            } 
//       }
//   else
//        {
//        if ( softstop > softstop_step )
//            {
//            softstop -= softstop_step;
//            softstart = 0;
//            }
//        }
	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_CMP1_bm;      /* The interrupt flag has to be cleared manually */
}

ISR(TCA0_CMP2_vect)
{
	/* Ensure off wait for overflow for next cycle */
    WO1_set_level(false);
    WO0_set_level(false);
    Run_set_level(true);
	/* The interrupt flag has to be cleared manually */
	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_CMP2_bm;
}



///**********************************************************/
///*  Name        : PWM Generation           		          */
///*  Parameters  : Interrupt function                      */
///*  Returns     : none                                       */
///*  Function    : to set the PWM Pins based on value of cnt  */
///*                         WO0   WO1 */
///*                  OVF  =  0     0  */
///*                  CMP1 =  1     0  */
///*                  CMP2 =  0     0  */
///*                  CMP3 =  0     1  */
///* The points that are set are done in the user code                    */
///*  Waveform has Deadtime, soft start 10 Cycles, soft stop 10 Cycles    */
///*  hence the need to use the ints rather than the WF gen function  */
///*--------------------------------------------------------*/
//ISR(TCA0_OVF_vect)
//{
//	/* Insert your TCA overflow interrupt handling code */
//    WO1_set_level(false);
//    WO0_set_level(false);
//    Run_set_level(true);
//	/* The interrupt flag has to be cleared manually */
//	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_OVF_bm;
//}
//
//
//ISR(TCA0_CMP0_vect)
//{
//	/* Insert your TCA Compare 0 Interrupt handling code here */
//    if(SD_wait_cntr > MAX_SD_WAIT )
//        {
//        WO1_set_level(false);
//        WO0_set_level(true);
//        }
//    else
//        {
//        WO1_set_level(false);
//        WO0_set_level(false);
//        SD_wait_cntr++;
//        }
//    Run_set_level(true);
//	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_CMP0_bm;	/* The interrupt flag has to be cleared manually */
//}
//
//ISR(TCA0_CMP1_vect)
//{
//	/* Insert your TCA Compare 1 Interrupt handling code here */
//    WO0_set_level(false);
//    WO1_set_level(false);
//    Run_set_level(true);
// 
//    if(nEN_get_level() == PSU_ON ) 
//       {
//         if(SD_wait_cntr > MAX_SD_WAIT )
//            {
//           if( softstart < softstart_max )   /* softstart stepping up to desired level.*/
//            {
//            softstart++;
//            softstop = softstart;
//            }
//
////            if( softstart < Pwm_A_u16 )   /* softstart stepping up to desired level.*/
////               {
////               softstart += softstart_step;
////               softstop = softstart;
////               }
////           else
////               {
////               softstop = Pwm_A_u16;    /*set stop from max value */
////                }
//            } 
//       }
//   else
//        {
//        if ( softstop > softstop_step )
//            {
//            softstop -= softstop_step;
//            softstart = 0;
//            }
//        }
//	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_CMP1_bm;      /* The interrupt flag has to be cleared manually */
//}
//
//ISR(TCA0_CMP2_vect)
//{
//	/* Insert your TCA Compare 2 Interrupt handling code here */
//     if(SD_wait_cntr > MAX_SD_WAIT )
//        {
//        WO1_set_level(true);
//        WO0_set_level(false);
//        }
//     else
//        {
//        WO1_set_level(false);
//        WO0_set_level(false);
//        }            
//    Run_set_level(true);
//	/* The interrupt flag has to be cleared manually */
//	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_CMP2_bm;
//}
//

/**********************************************************/
/*  Name        : ISR(PORTB_PORT_vect)            		    */
/*  Parameters  : void                                      */
/*  Returns     : none                                      */
/*  Function    : to read teh external pins and act on edge changes   */
/*              Use a mask to check which pin changed       *//*                                                          */
/*--------------------------------------------------------*/
ISR(PORTB_PORT_vect)    
{
/*-------------------------------------------------------------------------*/
if(nSD_INTERRUPT)
    {
    if(nSD_get_level() == PSU_ON ) 
        {
        Run_set_level(false);           /* disable output while updating the PWM */
        WO1_set_level(false);           /* Turn off the output drives */
        WO0_set_level(false);
        softstart = 0;                  /* reset softstart */
        softstart_old = -1;                  /* reset softstart */
        TCA0.SINGLE.CNT = 0x0;          /* Count: 0x0 */
       }
    else
        {
         }
     nSD_CLEAR_INTERRUPT_FLAG;
    }

}

/**********************************************************/
/*  Name        : ISR(PORTC_PORT_vect)            		    */
/*  Parameters  : void                                      */
/*  Returns     : none                                      */
/*  Function    : to read the external pins and act on edge changes   */
/*              Use a mask to check which pin changed       */
/*                                                          */
/*--------------------------------------------------------*/
ISR(PORTC_PORT_vect)    
{
 /*-------------------------------------------------------------------------*/
// if(nEN_INTERRUPT)    
//    {
//    if(nEN_get_level() == PSU_ON )      /* enable edge detected reset softstart*/
//       {
//        softstart = 1;
//        softstart_old = -1;                  /* reset softstart */
// 
//        }
//    else
//        {
//        if(softstart < softstart_max)
//            {
//            softstop = softstart;       /* turn off from last start value */
//            }
//        else
//            {
//            softstop = softstop_max;        /* set start point for decreasing from Current PWM */
//            }
//        }

//    if(nEN_get_level() == PSU_ON )      /* enable edge detected reset softstart*/
//        {
//        WO0_set_level(false);
//        WO1_set_level(false);
//        Run_set_level(true);
//        }
//    else     /* enable edge detected reset softstart*/
//        {
//        WO0_set_level(false);
//        WO1_set_level(false);
//        Run_set_level(true);
//        }
 
//    }
    
//    nEN_CLEAR_INTERRUPT_FLAG;
//    }
    
    if(Freq_INTERRUPT) {
        if (freq_get_level == HIGH_FREQUENCY_MARK)
        {
            set_PWM_2();
        }
        else
        {
            set_PWM_1();
        }
    }
    Freq_CLEAR_INTERRUPT_FLAG;
}

/**********************************************************/
/*  Name        : ISR(AC0_AC_vect)            		    */
/*  Parameters  : void                                      */
/*  Returns     : none                                      */
/*  Function    : To turn off the H-Drive if Current to high  */
/*              Vref 0.55V                                */
/*--------------------------------------------------------*/

/*-------------------------------------------------------------------------*/
ISR(AC0_AC_vect)
{
	/* Insert your AC interrupt handling code here */
        WO1_set_level(false);           /* Turn off the output drives */
        WO0_set_level(false);
        I_Limit_cntr++;
 
	/* The interrupt flag has to be cleared manually */
	AC0.STATUS = AC_CMP_bm;
}



/**********************************************************/
/* END OF FILE driver_isr.c                                */
/**********************************************************/

